receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md
    # We have to set defaults labels to false and we need to build them on promtail side.
    # default_labels_enabled:
      # job: false
      # exporter: false
  prometheus:
    endpoint: 0.0.0.0:8889
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true

processors:
  batch:
  attributes/loki:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: event.domain, event.name, container.name
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name, service.namespace

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp/logs]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]